#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#

import curses
import time

myscreen = curses.initscr()

curses.noecho()
#curses.start_color()
myscreen.border(0)
myscreen.addstr(12, 25, "Python curses in action!")
myscreen.getch()
#curses.init_pair(1, curses.COLOR_CYAN, curses.COLOR_BLACK)
myscreen.addstr(13, 25, "A-ha! I did it!")
myscreen.getch()
myscreen.refresh()
myscreen.addstr(14, 25, "Didn't think I could do it, did ya?")
time.sleep(1)
curses.flash()
myscreen.refresh()
curses.setsyx(13,25)
myscreen.clrtoeol()
myscreen.addstr(13, 25, "It appears I can replace stuff. How about line 12?")
myscreen.refresh()
time.sleep(1)
curses.setsyx(12,25)
myscreen.clrtoeol()
myscreen.refresh()
time.sleep(2)
myscreen.addstr(12, 25, "Awwww yes!")
pos = curses.getsyx()
touch = myscreen.getch()
if touch == ord('n'):
    myscreen.addstr(15, 25, "You just pressed n! No way!") 
    myscreen.getch()
else:
    pass

myscreen.addstr(17, 25, "You were at %s" % str(pos))
myscreen.getch()

curses.endwin()

