#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#

from sys import argv
from os import rename, remove

script, pfile = argv
	
bakfile = pfile+'.bak'
rename(pfile, bakfile)
fi = open(bakfile, 'r+')
fo = open(pfile, 'w+')
words = fi.read().splitlines()
for word in words:
    new_word = bytes.fromhex(word).decode('utf-8') 
    fo.write(new_word + '\n')
remove(bakfile)


