#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#

from sys import argv
from os import rename, remove
script, pfile = argv

bakfile = pfile+'.bak'
rename(pfile, bakfile)
fi = open(bakfile, 'r+')
fo = open(pfile, 'w+')
words = fi.read().splitlines()
for word in words:
    new_word = word.encode('hex')
    fo.write(new_word + '\n')
remove(bakfile)
	

